In [1]:
import cv2
import numpy as np
import pickle
import matplotlib.pyplot as plt
%matplotlib inline
import time

In [2]:
def showImg(img, title = ''):
    plt.figure(figsize = (10,10));
    plt.title(title)
    plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

def showGrayScaleImg(img, title = ''):
    plt.figure(figsize = (10,10));
    plt.title(title)
    plt.imshow(img, cmap='gray')

all_contours = -1
green = (0,255,0)
thickness = 2

In [3]:
#load the model
with open('cnn_model_450_Jan.pkl', 'rb') as p_f:
    model = pickle.load(p_f)

Using TensorFlow backend.
/Users/yok3r/anaconda3/envs/AkademyAI/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/yok3r/anaconda3/envs/AkademyAI/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/yok3r/anaconda3/envs/AkademyAI/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/yok3

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [4]:
image_template = cv2.imread('edgar.jpeg')

In [5]:
img = cv2.resize(image_template, (450,450))
#img = np.resize(img, (450,450,3))
im2arr = np.array(img)
im2arr1 = im2arr.reshape(1,450,450,3)

In [6]:
predictions = model.predict(im2arr1)
#predictions = predictions[0][0]
predictions
    
print(predictions)    
print (text)

[[2.8342487e-05 1.5578918e-04 9.9981588e-01]]


NameError: name 'text' is not defined

In [4]:
cap = cv2.VideoCapture(0)
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
i=0
while True:

    # Get webcam images
    ret, frame = cap.read()

    height, width = frame.shape[:2]

    top_left_x = width // 3
    top_left_y = (height // 2) + (height // 4)
    bottom_right_x = (width // 3) * 2
    bottom_right_y = (height // 2) - (height // 4)

    faces = face_classifier.detectMultiScale(frame, 1.3, 5)
    #print(faces)
    
    for (x,y,w,h) in faces:
    
        

        magin = 100
        top_left_x = x-magin
        top_left_y = y-magin
        bottom_right_x = x+w+magin
        bottom_right_y = y+w+magin


        cropped = frame[top_left_y:bottom_right_y, top_left_x:bottom_right_x]
        i+=1
        cv2.imwrite('save/eva'+str(i)+'.jpeg',cropped)
        cv2.rectangle(frame, (x,y),(x+w,y+w), (127,0,255), 2)
        
        try:
            #color_eva= cv2.cvtColor(cropped,cv2.COLOR_BGR2RGB)
            
            img = cv2.resize(cropped, (450,450))
            #img = np.resize(img, (450,450,3))
            im2arr = np.array(img)
            im2arr1 = im2arr.reshape(1,450,450,3)

            

            time.sleep(0.005) 
            predictions = model.predict(im2arr1)
            print(predictions)
            text = str(predictions)
            """
            if predictions < 0.0000001:
                text = "EDGAR"
            elif predictions > 0.99999:
                text = "EVA"
            else:
                text = "patata"
            """
            text_pred = str(predictions)
            cv2.putText(frame,text,(30,70), cv2.FONT_HERSHEY_COMPLEX, 0.6 ,(255,255,255), 3)
            #cv2.putText(frame,text_pred,(30,110), cv2.FONT_HERSHEY_COMPLEX, 2 ,(255,255,255), 6)
            
        except Exception as e:
            print(str(e))

        
    ####
    #DETECTTION CODE
    ####
    cv2.imshow('Object Detector using ORB', frame)
    
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break

cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)

[[3.521979e-20 2.467858e-23 1.000000e+00]]
[[3.138860e-23 1.362664e-13 1.000000e+00]]
[[2.4389298e-23 6.2044185e-12 1.0000000e+00]]
[[1.7166160e-24 2.5209084e-12 1.0000000e+00]]
[[1.0411712e-26 1.8283825e-15 1.0000000e+00]]
[[8.3432714e-24 2.0402131e-12 1.0000000e+00]]
[[1.7154713e-23 1.7608111e-12 1.0000000e+00]]
[[3.2616033e-18 4.6789776e-22 1.0000000e+00]]
[[1.2513543e-18 5.0188501e-23 1.0000000e+00]]
[[9.980554e-33 9.894361e-16 1.000000e+00]]
[[1.4775495e-22 8.2640736e-26 1.0000000e+00]]
[[4.9367635e-23 3.5964762e-12 1.0000000e+00]]
[[2.0898872e-07 2.7596606e-19 9.9999976e-01]]
[[1.3319958e-11 1.2895490e-13 1.0000000e+00]]
[[4.6639206e-14 1.7367132e-15 1.0000000e+00]]
[[1.1644381e-08 1.7537059e-19 1.0000000e+00]]
[[7.6794585e-27 8.3626785e-16 1.0000000e+00]]
[[5.3710376e-18 7.4330305e-19 1.0000000e+00]]
[[1.04084213e-10 7.50783181e-20 1.00000000e+00]]
[[9.510732e-18 3.714879e-25 1.000000e+00]]
[[9.8903612e-16 6.6185535e-16 1.0000000e+00]]
[[6.1338956e-10 3.8803377e-31 1.0000000e+00

OpenCV(3.4.2) /opt/concourse/worker/volumes/live/9523d527-1b9e-48e0-7ed0-a36adde286f0/volume/opencv-suite_1535558719691/work/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

[[0.01981883 0.96018255 0.01999855]]
OpenCV(3.4.2) /opt/concourse/worker/volumes/live/9523d527-1b9e-48e0-7ed0-a36adde286f0/volume/opencv-suite_1535558719691/work/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

OpenCV(3.4.2) /opt/concourse/worker/volumes/live/9523d527-1b9e-48e0-7ed0-a36adde286f0/volume/opencv-suite_1535558719691/work/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

OpenCV(3.4.2) /opt/concourse/worker/volumes/live/9523d527-1b9e-48e0-7ed0-a36adde286f0/volume/opencv-suite_1535558719691/work/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'



-1